name: Build ZMK firmware
on: [workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
    with:
      build_matrix_path: "Firmware/boards.yaml"
      config_path: "Firmware/config"